### ISSUE TITLE
Index 002-FJ-2020 image-tag 0.0.1-16-ge972c7d

### ISSUE THREAD

**Issue by nicholasmetherall** [digitalearthpacific/dep-mangroves#4]
/usr/lib/python3/dist-packages/osgeo/osr.py:388: FutureWarning: Neither osr.UseExceptions() nor osr.DontUseExceptions() has been explicitly
called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
/usr/lib/python3/dist-packages/osgeo/osr.py:388: FutureWarning: Neither osr.UseExceptions() nor osr.DontUseExceptions() has been explicitly
called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
/usr/lib/python3/dist-packages/osgeo/osr.py:388: FutureWarning: Neither osr.UseExceptions() nor osr.DontUseExceptions() has been explicitly
called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
/usr/lib/python3/dist-packages/osgeo/osr.py:388: FutureWarning: Neither osr.UseExceptions() nor osr.DontUseExceptions() has been explicitly
called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
/usr/lib/python3/dist-packages/osgeo/osr.py:388: FutureWarning: Neither osr.UseExceptions() nor osr.DontUseExceptions() has been explicitly
called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
  0%|          | 0/1 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/rasterio/warp.py:344: NotGeoreferencedWarning: Dataset has no g
eotransform, gcps, or rpcs. The identity matrix will be returned.
  _reproject(
/usr/local/lib/python3.10/dist-packages/rasterio/warp.py:344: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The ident
ity matrix will be returned.
  _reproject(
/usr/local/lib/python3.10/dist-packages/rasterio/warp.py:344: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The ident
ity matrix will be returned.
  _reproject(
/usr/local/lib/python3.10/dist-packages/rasterio/warp.py:344: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The ident
ity matrix will be returned.
  _reproject(
2023-09-08 02:45:37,923 - distributed.nanny - WARNING - Restarting worker
2023-09-08 02:45:38,137 - distributed.worker - ERROR - failed during get data with tcp://127.0.0.1:33779 -> tcp://127.0.0.1:34235
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 962, in _handle_write

**Comment by nicholasmetherall** [comment]
The part I believe is the most important:

```
W
Traceback (most recent call last):
  File "/code/src/run_task.py", line 110, in <module>
    typer.run(main)
  File "/code/src/run_task.py", line 98, in main
    run_by_area_dask_local(
  File "/usr/local/lib/python3.10/dist-packages/dep_tools/runner.py", line 122, in run_by_area_dask_local
    run_by_area(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dep_tools/runner.py", line 104, in run_by_area
    ).run()
  File "/usr/local/lib/python3.10/dist-packages/dep_tools/runner.py", line 69, in run
    raise e
  File "/usr/local/lib/python3.10/dist-packages/dep_tools/runner.py", line 64, in run
    output_data = self.processor.process(input_data, **processor_kwargs)
  File "/code/src/run_task.py", line 40, in process
    .compute()
  File "/usr/local/lib/python3.10/dist-packages/xarray/core/dataset.py", line 991, in compute
    return new.load(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xarray/core/dataset.py", line 825, in load
    evaluated_data = chunkmanager.compute(*lazy_data.values(), **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xarray/core/daskmanager.py", line 70, in compute
    return compute(*data, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/distributed/client.py", line 2252, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: Attempted to run task ('rechunk-split-768661aedf1712fa3d682adf2db42955', 3122) on 3 different workers, b
ut all those workers died while running it. The last worker that attempt to run the task was tcp://127.0.0.1:46099. Inspecting worker logs i
s often a good next step to diagnose what went wrong. For more information see https://distributed.dask.org/en/stable/killed.html.
time="2023-09-08T02:59:16 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1

```

**Comment by nicholasmetherall** [comment]
The entire log 
[Errors_08092023.txt](https://github.com/digitalearthpacific/dep-mangroves/files/12555158/Errors_08092023.txt)

**Comment by alexgleith** [comment]
Relevant Dask config is this:

```
--local-cluster-kwargs "{'n_workers':4, 'memory_limit':'16GiB', 'threads_per_worker': 4}"
```

**Comment by jessjaco** [comment]
In a dream last night I saw a yaml posted here that only gave 16GiB workers 15GiB of memory. Could that be true?

**Comment by alexgleith** [comment]
> only gave 16GiB workers 15GiB of memory

There's "request" and "limit". The "request" is what is guaranteed to be available and the "limit" is the threshold for the container to be destroyed with prejudice!

The container has a hard limit of 20GB, so won't have had a problem getting the 16 GB dask was asking for: https://github.com/digitalearthpacific/dep-kubernetes-apps/blob/36af6104c896a908200620ab70194eb2db62c055/workflows/staging/once/mangroves-annual.yaml#L110
