### ISSUE TITLE
Index 004-FJ-2020 image-tag 0.0.1-16-ge972c7d help wanted 

### ISSUE THREAD

**Issue by nicholasmetherall** [digitalearthpacific/dep-mangroves#5]
W
/usr/lib/python3/dist-packages/osgeo/osr.py:388: FutureWarning: Neither osr.UseExceptions() nor osr.DontUseExceptions() has been explicitly
called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
Traceback (most recent call last):
  File "/code/src/run_task.py", line 110, in <module>
    typer.run(main)
  File "/code/src/run_task.py", line 70, in main
    area = get_gmw_shapes_for_area(cell)
  File "/code/src/run_task.py", line 57, in get_gmw_shapes_for_area
    return gmw.clip(area.to_crs(gmw.crs)).dissolve("PXLVAL").set_index(area.index)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 5924, in set_index
    raise ValueError(
ValueError: Length mismatch: Expected 0 rows, received array of length 1
time="2023-09-08T02:44:57 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1

**Comment by nicholasmetherall** [comment]
This one seems to just be about the length of the array. Do we just need to change the lengths of the arrays to match?

**Comment by jessjaco** [comment]
This is due to no mangroves being in the cell, I will need to fix

**Comment by nicholasmetherall** [comment]
parameters info: 

image-tag 0.0.1-16-ge972c7d

Index 004
Country FJ
Year 2020 

Other info from the yaml file:
[Yaml_08092023.txt](https://github.com/digitalearthpacific/dep-mangroves/files/12555165/Yaml_08092023.txt)

**Comment by nicholasmetherall** [comment]
args:
        - src/run_task.py
        - --region-code
        - "{{ inputs.parameters.region-code }}"
        - --region-index
        - "{{ inputs.parameters.region-index }}"
        - --datetime
        - "{{ inputs.parameters.year }}"
        - --version
        - "{{ inputs.parameters.version }}"
        - --local-cluster-kwargs
        - "{'n_workers':4, 'memory_limit':'16GiB', 'threads_per_worker': 4}"
